In [ ]:
import sqlite3
import pandas as pd
# Create your connection.
cnx = sqlite3.connect('../sql_mqtt_data_log/sensor.db')

df_walking = pd.read_sql_query("SELECT * FROM ction", cnx)
#df_standing = pd.read_sql_query("SELECT * FROM standing", cnx)
#df_complete=pd.concat([df_walking,df_standing],axis=0)

In [3]:
#print(df_walking.head())
#print(df_standing.head())
df_walking


id  timestamp  top_accel_x  top_accel_y  top_accel_z  top_mag_x  \
0      1   810761.0      -224.43       -87.10     -1091.92     -17.16   
1      2   810818.0      -228.45       -89.90     -1090.94     -16.98   
2      3   810875.0      -227.66       -85.82     -1087.77     -17.39   
3      4   810930.0      -228.64       -87.89     -1090.09     -17.53   
4      5   810986.0      -226.56       -84.90     -1085.94     -17.22   
5      6   811042.0      -227.17       -86.67     -1090.82     -17.01   
6      7   811099.0      -228.03       -85.57     -1088.26     -17.18   
7      8   811155.0      -228.09       -87.22     -1090.09     -17.20   
8      9   811213.0      -227.36       -86.73     -1092.29     -17.37   
9     10   811272.0      -226.14       -87.22     -1088.07     -17.42   
10    11   811328.0      -227.60       -85.75     -1089.11     -17.19   
11    12   811385.0      -227.78       -86.49     -1090.15     -17.14   
12    13   811440.0      -226.93       -86.98     -1092.41     -17.43   
13    14   811496.0      -226.75       -87.22     -1092.22     -17.48   
14    15   811552.0      -229.61       -88.75     -1093.93     -17.23   
15    16   811608.0      -227.66       -84.29     -1090.70     -17.19   
16    17   811664.0      -227.60       -85.94     -1091.19     -17.10   
17    18   811720.0      -226.62       -85.27     -1085.51     -17.24   
18    19   811776.0      -226.14       -86.06     -1093.32     -17.11   
19    20   811833.0      -224.30       -81.42     -1090.64     -17.85   
20    21   811889.0      -228.64       -90.64     -1096.19     -16.11   
21    22   811946.0      -230.59       -82.03     -1092.77     -16.49   
22    23   812002.0      -228.88       -89.42     -1090.21     -16.37   
23    24   812057.0      -227.29       -83.50     -1091.13     -17.06   
24    25   812145.0      -224.12       -89.48     -1093.32     -17.80   
25    26   812201.0      -224.30       -84.11     -1090.39     -17.24   
26    27   812257.0      -226.01       -88.93     -1090.21     -16.67   
27    28   812313.0      -221.86       -86.55     -1091.31     -17.10   
28    29   812369.0      -227.11       -87.83     -1093.02     -17.54   
29    30   812424.0      -226.56       -86.73     -1093.14     -17.44   
..   ...        ...          ...          ...          ...        ...   
167  168   824853.0      -225.34       -85.75     -1091.74     -17.34   
168  169   824923.0      -228.94       -87.89     -1091.86     -17.38   
169  170   824978.0      -225.22       -88.38     -1094.60     -17.36   
170  171   825034.0      -228.82       -83.50     -1090.58     -17.38   
171  172   825090.0      -226.50       -86.06     -1091.06     -17.18   
172  173   825145.0      -224.61       -85.27     -1087.28     -17.37   
173  174   825202.0      -227.78       -84.53     -1088.50     -17.30   
174  175   825256.0      -225.77       -88.38     -1090.64     -17.35   
175  176   825316.0      -223.57       -85.14     -1089.78     -17.23   
176  177   825372.0      -226.93       -88.38     -1089.78     -17.27   
177  178   825449.0      -225.34       -88.32     -1087.83     -17.21   
178  179   825505.0      -224.12       -84.96     -1088.62     -17.33   
179  180   825561.0      -223.51       -86.18     -1090.58     -17.25   
180  181   825616.0      -227.60       -85.75     -1091.61     -17.11   
181  182   825671.0      -223.82       -85.88     -1090.58     -17.13   
182  183   825727.0      -228.27       -85.14     -1091.80     -17.20   
183  184   825783.0      -227.23       -87.65     -1087.95     -17.26   
184  185   825840.0      -225.71       -86.12     -1091.80     -17.20   
185  186   825895.0      -224.73       -86.79     -1090.70     -17.26   
186  187   825950.0      -225.59       -84.96     -1092.71     -17.22   
187  188   826006.0      -226.75       -87.83     -1091.06     -17.40   
188  189   826061.0      -225.16       -86.85     -1088.44     -17.24   
189  190   826117.0      -227.97       -86.00     -1088.93     -

In [95]:

import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import tensorflow as tf  # Version 1.0.0 (some previous versions are used in past commits)
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from keras.layers import Dense, Dropout, LSTM, Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from sklearn.metrics import classification_report,confusion_matrix

import os

In [97]:
X_train=df_complete.drop(['action','id','bottom_temperature','top_temperature','timestamp'],axis=1)
Y_train=df_complete['action']
#Y_train[Y_train=='walking']=0
#Y_train[Y_train=='standing']=1
Y_train=pd.get_dummies(Y_train)
X_train=(X_train-X_train.min())/(X_train.max()-X_train.min())
X_train, X_test, Y_train, Y_test = train_test_split(X_train, Y_train, test_size=0.2)
X_train=X_train.values
Y_train=Y_train.values
X_test=X_test.values
Y_test=Y_test.values
Y_test

array([[0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0,

In [98]:
def create_model(input_length):
    print ('Creating model...')
    model = Sequential()
    model.add(Embedding(input_dim = 188, output_dim = 50, input_length = input_length))
    model.add(LSTM(output_dim=256, activation='sigmoid', inner_activation='hard_sigmoid', return_sequences=True))
    model.add(Dropout(0.5))
    model.add(LSTM(output_dim=256, activation='sigmoid', inner_activation='hard_sigmoid'))
    model.add(Dropout(0.5))
    model.add(Dense(2, activation='softmax'))

    print ('Compiling...')
    model.compile(loss='binary_crossentropy',
                  optimizer='rmsprop',
                  metrics=['accuracy'])
    return model
model = create_model(len(X_train[0]))

Creating model...


/home/kenny/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(activation="sigmoid", return_sequences=True, units=256, recurrent_activation="hard_sigmoid")`
  """
/home/kenny/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(activation="sigmoid", units=256, recurrent_activation="hard_sigmoid")`
  import sys


Compiling...


In [99]:
hist = model.fit(X_train, Y_train, batch_size=10, epochs=10, validation_split = 0.1, verbose = 1)

score, acc = model.evaluate(X_test, Y_test, batch_size=1)
print('Test score:', score)
print('Test accuracy:', acc)

Train on 386 samples, validate on 43 samples
Epoch 1/10
386/386 [==============================] - 6s 15ms/step - loss: 0.7620 - acc: 0.6114 - val_loss: 0.6942 - val_acc: 0.5581
Epoch 2/10
386/386 [==============================] - 4s 12ms/step - loss: 0.6953 - acc: 0.6088 - val_loss: 0.7223 - val_acc: 0.5581
Epoch 3/10
386/386 [==============================] - 4s 12ms/step - loss: 0.6710 - acc: 0.6554 - val_loss: 0.7300 - val_acc: 0.5581
Epoch 4/10
386/386 [==============================] - 5s 12ms/step - loss: 0.6727 - acc: 0.6554 - val_loss: 0.7633 - val_acc: 0.5581
Epoch 5/10
386/386 [==============================] - 6s 16ms/step - loss: 0.6454 - acc: 0.6684 - val_loss: 0.7386 - val_acc: 0.5581
Epoch 6/10
386/386 [==============================] - 6s 15ms/step - loss: 0.6580 - acc: 0.6580 - val_loss: 0.8518 - val_acc: 0.5581
Epoch 7/10
386/386 [==============================] - 5s 13ms/step - loss: 0.6410 - acc: 0.6736 - val_loss: 0.7467 - val_acc: 0.5581
Epoch 8/10
386/386 [====

In [100]:
Y_pred=model.predict(X_test)


In [102]:
Y_pred = np.argmax(Y_pred,axis = 1) 
Y_test=np.argmax(Y_test,axis=1)

In [104]:
print('Test set classification report:\n{}'.format(classification_report(Y_test, Y_pred)))
print('Confusion Matrix:\n{}'.format(confusion_matrix(Y_test, Y_pred)))
Y_pred

Test set classification report:
             precision    recall  f1-score   support

          0       0.64      1.00      0.78        69
          1       0.00      0.00      0.00        39

avg / total       0.41      0.64      0.50       108

Confusion Matrix:
[[69  0]
 [39  0]]


/home/kenny/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])